name: CI

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: setup node
        uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: "npm"

      - name: install Rust stable
        uses: dtolnay/rust-toolchain@stable

      - name: Rust cache
        uses: swatinem/rust-cache@v2
        with:
          workspaces: "./src-tauri -> target"

      - name: Install dependencies (backend and frontend)
        run: |
          npm install
          npm install --prefix client

      - name: TypeScript type check
        run: npx tsc --noEmit

      - name: Frontend lint
        run: npm run lint --prefix client

      - name: Frontend build
        run: npm run build --prefix client

      - name: Rust tests
        run: cargo test --manifest-path src-tauri/Cargo.toml
